# Generated by Django 5.1.15 on 2026-01-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Role or education title, e.g. "Software Engineering Intern"', max_length=200)),
                ('organization', models.CharField(help_text='Company / University / Team name', max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if ongoing', null=True)),
                ('highlights', models.TextField(blank=True, help_text='Write one bullet per line. Example:\n- Did X\n- Built Y\n- Improved Z')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(help_text='Project start date')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if ongoing', null=True)),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated tags, e.g. "Python, OpenCV, MediaPipe"', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
