# Generated by Django 6.0.2 on 2026-03-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_community_competition_education_project_demo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description_en',
            field=models.TextField(blank=True, help_text='Short summary (EN)'),
        ),
        migrations.AddField(
            model_name='community',
            name='highlights_en',
            field=models.TextField(blank=True, help_text='Highlights (EN)'),
        ),
        migrations.AddField(
            model_name='community',
            name='name_en',
            field=models.CharField(blank=True, help_text='Club name (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='community',
            name='role_en',
            field=models.CharField(blank=True, help_text='Role (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='competition',
            name='award_en',
            field=models.CharField(blank=True, help_text='Award (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_en',
            field=models.TextField(blank=True, help_text='Short summary (EN)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='highlights_en',
            field=models.TextField(blank=True, help_text='Highlights (EN)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='role_en',
            field=models.CharField(blank=True, help_text='Your role (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='competition',
            name='title_en',
            field=models.CharField(blank=True, help_text='Competition name (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(blank=True, help_text="Degree (EN): Bachelor's, Master's…", max_length=160),
        ),
        migrations.AddField(
            model_name='education',
            name='department_en',
            field=models.CharField(blank=True, help_text='Department (EN)', max_length=160),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(blank=True, help_text='Notes (EN) — boşsa TR kullanılır'),
        ),
        migrations.AddField(
            model_name='education',
            name='school_en',
            field=models.CharField(blank=True, help_text='School name (EN)', max_length=160),
        ),
        migrations.AddField(
            model_name='experience',
            name='highlights_en',
            field=models.TextField(blank=True, help_text='Highlights (EN) — boşsa TR kullanılır'),
        ),
        migrations.AddField(
            model_name='experience',
            name='organization_en',
            field=models.CharField(blank=True, help_text='Organization (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='long_description_en',
            field=models.TextField(blank=True, help_text='Modal description (EN) — boşsa TR kullanılır'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_en',
            field=models.CharField(blank=True, help_text='Role (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Card summary (EN) — boşsa TR kullanılır', max_length=220),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title (EN) — boşsa TR kullanılır', max_length=200),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, help_text='Kısa özet (TR)'),
        ),
        migrations.AlterField(
            model_name='community',
            name='highlights',
            field=models.TextField(blank=True, help_text='Maddeler (TR)'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(help_text='Kulüp adı (TR)', max_length=200),
        ),
        migrations.AlterField(
            model_name='community',
            name='role',
            field=models.CharField(blank=True, help_text='Rolün (TR): Üye, Çekirdek Ekip…', max_length=200),
        ),
        migrations.AlterField(
            model_name='competition',
            name='award',
            field=models.CharField(blank=True, help_text='Derece/ödül (TR): Finalist, 2. lik', max_length=200),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, help_text='Kısa özet (TR)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='highlights',
            field=models.TextField(blank=True, help_text='Maddeler (TR)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='role',
            field=models.CharField(blank=True, help_text='Rolün (TR)', max_length=200),
        ),
        migrations.AlterField(
            model_name='competition',
            name='team_members',
            field=models.TextField(blank=True, help_text='Satır başına bir kişi'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(help_text='Yarışma adı (TR)', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, help_text='Derece (TR): Lisans, Yüksek Lisans…', max_length=160),
        ),
        migrations.AlterField(
            model_name='education',
            name='department',
            field=models.CharField(blank=True, help_text='Bölüm (TR)', max_length=160),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, help_text='Notlar / maddeler (TR)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(help_text='Okul adı (TR)', max_length=160),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='Devam ediyorsa boş bırak', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='highlights',
            field=models.TextField(blank=True, help_text='Madde madde, satır başına bir madde (TR):\n- Yaptım X\n- Geliştirdim Y'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.CharField(help_text='Şirket / Üniversite (TR)', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(help_text='Pozisyon (TR): "Yazılım Mühendisi Stajyeri"', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Devam ediyorsa boş bırak', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Öne çıkan projelerde göster'),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, help_text='Modal açıklama (TR)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Örn: "Raidyn Team | Otonom Navigasyon" (TR)', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='Kart özeti (TR)', max_length=220),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='Proje başlangıç tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Virgülle ayır: "Python, OpenCV, MediaPipe"', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Başlık (TR)', max_length=200),
        ),
    ]
